### ISSUE TITLE
Documentation:  Roxygen headers fill in values, examples or set to internal

### ISSUE THREAD

**Issue by bms63** [pharmaverse/logrx#106]
### Let us know where something needs a refresh or put your idea here!

Any non-user facing functions should be set to internal and not be shown on the packagdown site.

If they are shown on the site, then they should be well-documented with examples, filled out header and arguments, etcs.

**Comment by thomasp-b** [comment]
@nicholas-masel, `approved_functions_init()`'s documentation implies that the function can be used to set up the `logrx.approved` option to a folder other than the working directory however that isn't possible in the function's current form. Shall we open an issue to implement the functionality (it is desirable?) or shall I rephrase the documentation?

**Comment by kodesiba** [comment]
> @nicholas-masel, `approved_functions_init()`'s documentation implies that the function can be used to set up the `logrx.approved` option to a folder other than the working directory however that isn't possible in the function's current form. Shall we open an issue to implement the functionality (it is desirable?) or shall I rephrase the documentation?

@thomasp-b we will be moving this to options that are set onload so users will just be able to set that option to whatever they would like and then function will use it. See https://github.com/atorus-research/logrx/pull/112#issuecomment-1210910632 for what the update will be
