### ISSUE TITLE
Documentation:  add context for when to use lint option

### ISSUE THREAD

**Issue by nicholas-masel** [pharmaverse/logrx#124]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

Add to the options vignette to highlight when you might want to use the lint option.

**Comment by kodesiba** [comment]
@nicholas-masel @bms63 @thomasp-b this issue got me thinking, is there any other code formatting pieces we want to integrate?  I know linting is the most popular but there are things like `spelling` that people use on top of linting

**Comment by bms63** [comment]
I like spelling checks!

**Comment by nicholas-masel** [comment]
@thomasp-b @kodesiba @bms63 I will hold off on this one until #105 is complete.
