### ISSUE TITLE
Documentation:  Output clarification

### ISSUE THREAD

**Issue by aehmann-gsk** [pharmaverse/logrx#142]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

This looks like a great solution! I am excited to see this brought into our frozen environment.  

For the output presented in the .log, it only shows the last item that is output in the script, for example,

```
x <- head(adae, n=2)
y <- "Alice"
z <- "Ben"
x
y
z
```
will only show "Ben" in the log.  You can put multiple objects into a `list` and write the that way at the end of the code as well (e.g. `list(x, y, z)`) It looks to me like it will pick up `glimpse` statements anywhere in the code.  However, if I put a `count(adae, STUDYID)` in the code it is not picked up by the output. Perhaps a bit more documentation on what gets picked up for the output section of the `.log` file?

**Comment by nicholas-masel** [comment]
@aehmann-gsk  I think wrapping it in `print()` will send everything to output.

**Comment by bms63** [comment]
Will be addressed in #178
