### ISSUE TITLE
`get_library()` incorrectly returns non-function objects if found

### ISSUE THREAD

**Issue by nicholas-masel** [pharmaverse/logrx#154]
### What happened?

If an object is set that is the same name as a function, and that object is higher in the search path than the function, logrx records that you have used this object, instead of recording the function you actually used.

Recommend updating so `get_library()` will check the object structure for functions [here](https://github.com/pharmaverse/logrx/blob/main/R/get.R#L220).

### Session Information

N/A

### Reproducible Example

```r
write_file('search <- "dummy object"', "dummy.R", ".")

sys.source("dummy.R", envir = attach(NULL, name = "dummy"))

search()
```

axecute the code above and logrx will show you used dummy:search instead of base:search

``` 
--------------------------------------------------------------------------------
-                          Used Package and Functions                          -
--------------------------------------------------------------------------------
{dummy} search
{package:base} sys.source, attach
```

**Comment by bms63** [comment]
@kodesiba I noticed this behavior as well in a demo I was doing for `admiral`.  I think we should prioritize fixing this.
