### ISSUE TITLE
Feature Request:  Consider mandatory lint for library calls to be at top of script

### ISSUE THREAD

**Issue by nicholas-masel** [pharmaverse/logrx#163]
### Feature Idea

We have linting now, we could add a linter that would always fire to make sure all library calls are at the top of the script.  This is critical to ensuring the functions used is accurate, since the search path would be set and stay the same from the beginning to the end of the script.

**Comment by bms63** [comment]
* Possible warning to user on improrper use of `library()`
*  `**` warning in approved package section on placement of library() call

**Comment by nicholas-masel** [comment]
I'm making this so it is always on.  We can chat about this one at our next meeting.

I have included `library_call_linter()` as a logrx function, but this is now in [lintr ](https://github.com/r-lib/lintr/pull/2027).  I'll remove it from here after the next lintr release.
