### ISSUE TITLE
Feature Request:  Capture base URLs of repos

### ISSUE THREAD

**Issue by parmsam-pfizer** [pharmaverse/logrx#167]
### Feature Idea

We're not currently capturing the base URLs of repos. Recently submitted [an issue to {sessioninfo}](https://github.com/r-lib/sessioninfo/issues/81#issuecomment-1453289762) about this but it was rejected. Logging this info would be useful to ensure the original R repositories(s) is/are used to recreate execution environments. It's captured in [renv lockfiles](https://rstudio.github.io/renv/articles/lockfile.html). Creating this issue to get others thoughts on this idea. 

### Reproducible Example/Pseudo Code

```
get_repo_urls <- function() {
  as.list(getOption("repos"))
}
```

**Comment by bms63** [comment]
Tack onto bottom of session Information, but don't interfere with session object.
