### ISSUE TITLE
Does {logrx} work with Rscript?

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/logrx#200]
I've seen that you can make use of {logrx} when using `Rscript` like so `Rscript -e "axecute('my_file.R')"`. However, what about the case where the R script itself takes command line arguments by making use of {optparse} or other packages? Let's say my script has a `pop-filter` argument and usually I would call it like `Rscript my_script.R --pop-filter "SAFFL == 'Y'"`. With the current design is there any way to leverage {logrx} in this case?

**Comment by nicholas-masel** [comment]
It seems possible.  I'm not familiar with {optparse} but I made a script, test.R, and just had it print `commandArgs(trailing = TRUE)`.

So I ran this:

`Rscript -e "logrx::axecute('test.R')" --pop-filter "SAFFL == 'Y'"`

And it returned:

`[1] "--pop-filter" "SAFFL == 'Y'"`

**Comment by kodesiba** [comment]
@thomas-neitmann does the above example from @nicholas-masel work?

**Comment by thomas-neitmann** [comment]
Thanks a lot for the suggestion @nicholas-masel. I hadn't even imagined that you could call `Rscript` with the `-e` option **and** be able to pass command line arguments to the script.

**Comment by nicholas-masel** [comment]
@thomas-neitmann  No problem!  Glad that worked for you.  I learned something new too.  That's the first I've see optparse.  I'm sure it will come in handy one day.
