### ISSUE TITLE
Feature for consideration:  Integrate with the `targets` library

### ISSUE THREAD

**Issue by billdenney** [pharmaverse/logrx#24]
This is a "feature for consideration" rather than going as far as being a "feature request" because I don't know if it would align with the goals of the project.

Much of my code takes a while to run (between minutes and hours), so I use the `targets` package (https://github.com/ropensci/targets) in almost all of my work.  I could imagine combining the efforts in `timber` and `targets` to capture the outputs and the session info, and to speed up repeated re-analysis that is often required via `targets`.

Would something like this be a fit?

Capturing the `sessionInfo()` within `targets` is discussed in ropensci/targets#676.

**Comment by bms63** [comment]
Hey Bill are you still interested in adding this feature?

**Comment by billdenney** [comment]
@bms63, Unfortunately, I don't have the bandwidth to take it on in the near future.

**Comment by bms63** [comment]
All good @billdenney!!  We are planning for logrx 0.4.0 release and seeing what we/others can tackle :)
