### ISSUE TITLE
Explore adding program checksum to log

### ISSUE THREAD

**Issue by kodesiba** [pharmaverse/logrx#29]
Add section to the log that is a computed checksum `digest::sha1()` of the file that is being run to if anyone would like to ensure that the log matches the file this verification can be made. https://cran.r-project.org/web/packages/digest/index.html

**Comment by bms63** [comment]
![image](https://user-images.githubusercontent.com/10111024/185809237-1ecbca09-8acb-45e6-aebb-4601192a2c84.png)

@nicholas-masel @kodesiba and @thomasp-b Just starting to play around with this.

Do we want this to appear in the User and File Information section?

What do want to call it?  HashSum?

![image](https://user-images.githubusercontent.com/10111024/185809275-863c6e10-34c3-4a17-b6d4-57d0dce1bdd4.png)

**Comment by kodesiba** [comment]
@bms63 this looks fine to me.  Only changes would be to move it to the bottom of the section and name it "File HashSum" so it's obvious what it is referring to
