### ISSUE TITLE
Documentation: Best Practices Template

### ISSUE THREAD

**Issue by bms63** [pharmaverse/logrx#33]
Optimizing your R Script to get the best log file from timber

- [ ]  Results only captures the last result - print statements are way to get more
- [ ]  Attach all libraries at the top of your scripts - this ensures all packages and functions are captured correctly
- [ ]  Use message() to print out custom messages to the log.

**Comment by nicholas-masel** [comment]
Extending what @bms63 has started.

[ ] Results only captures the last result - print statements are way to get more
[ ] Attach all libraries at the top of your scripts - this ensures all packages and functions are captured correctly
