### ISSUE TITLE
Integration with ```tidylog```

### ISSUE THREAD

**Issue by kodesiba** [pharmaverse/logrx#97]
Ran across the ```tidylog``` package which does an interesting set of things to log what is happening in main tidyverse functions.  This could be an interesting functionality. https://github.com/elbersb/tidylog

**Comment by bms63** [comment]
I think you have to wrap all your functions with this tidylog wrapper, which is tedious.  However, being able to turn on this feature to look at joins information would be hugely beneficial for users I think.

**Comment by kodesiba** [comment]
Definitely agree we don't want to make it internal but we might want to at least check if it works nicely with ```logrx``` since I can see people wanting this.

**Comment by Mia-data** [comment]
Logrx dose amazing job! I'm only missing capturing in the log information provided by tidylog, which force me to use another log package instead logrx.  I look forward to the logrx integration with tidylog!!!
